language: java

jdk:
  - oraclejdk8    
  
 # Enable initializing of GUI context required for running tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: 
 - wget http://www.codenameone.com/files/updatedLibs.zip
 - mkdir lib
 - unzip updatedLibs.zip -d lib
 - mv lib/JavaSE.jar .
 - wget http://www.codenameone.com/files/CodeNameOneBuildClient.jar
 - cat build.xml | sed "s~<codeNameOne~<codeNameOne userName=\"$cn1user\" password=\"$cn1password\"~" > build.tmp
 - cp -f build.tmp build.xml
 - ant -Dautomated=true -Dcn1user=$cn1user -Dcn1password=$cn1password build-for-javascript jar
