language: java

jdk:
  - oraclejdk8    
  
 # Enable initializing of GUI context required for running tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: 
 - wget http://www.codenameone.com/files/updatedLibs.zip
 - mkdir lib
 - unzip updatedLibs.zip -d lib
 - mv lib/JavaSE.jar .
 - wget http://www.codenameone.com/files/CodeNameOneBuildClient.jar
 - ant -Dautomated=true jar -Dcn1user=$cn1user -Dcn1password=$cn1password build-for-javascript
